using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CWPortable.PowerPC
{
    public static class Definitions
    {
        public static List<Instruction> Instructions = null;
        public static List<Extended> Extensions = null;

        public static bool Initialize()
        {
            if (Instructions == null)
                Instructions = new List<PowerPC.Instruction>();
            else
                Instructions.Clear();

            // -------------------------------------------------- A
            Instructions.Add(new Instruction("add", 0x7C000214, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("add.", 0x7C000215, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("addo", 0x7C000614, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("addo.", 0x7C000615, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("addc", 0x7C000014, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("addc.", 0x7C000015, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("addco", 0x7C000414, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("addco.", 0x7C000415, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("adde", 0x7C000114, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("adde.", 0x7C000115, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("addeo", 0x7C000514, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("addeo.", 0x7C000515, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("addi", 0x38000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("addic", 0x30000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("addic.", 0x34000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("addis", 0x3C000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("addme", 0x7C0001D4, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("addme.", 0x7C0001D5, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("addze", 0x7C000194, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("addze.", 0x7C000195, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("and", 0x7C000038, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("and.", 0x7C000039, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("andc", 0x7C000078, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("andc.", 0x7C000079, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("andi.", 0x70000000, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("andis.", 0x74000000, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            // -------------------------------------------------- B
            Instructions.Add(new Instruction("b", 0x48000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.BRANCHIMMEDIATERELATIVE, Length = 24 }));
            Instructions.Add(new Instruction("ba", 0x48000002, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.BRANCHIMMEDIATE, Length = 24 }));
            Instructions.Add(new Instruction("bl", 0x48000001, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.BRANCHIMMEDIATERELATIVE, Length = 24 }));
            Instructions.Add(new Instruction("bla", 0x48000003, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.BRANCHIMMEDIATE, Length = 24 }));
            Instructions.Add(new Instruction("bc", 0x40000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.CONDITIONREGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.BRANCHIMMEDIATERELATIVE, Length = 14 }));
            Instructions.Add(new Instruction("bca", 0x40000002, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.CONDITIONREGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.BRANCHIMMEDIATE, Length = 14 }));
            Instructions.Add(new Instruction("bcl", 0x40000001, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.CONDITIONREGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.BRANCHIMMEDIATERELATIVE, Length = 14 }));
            Instructions.Add(new Instruction("bcla", 0x40000003, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.CONDITIONREGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.BRANCHIMMEDIATE, Length = 14 }));
            Instructions.Add(new Instruction("bclr", 0x4C000020, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.CONDITIONREGISTER, Length = 5 }));
            Instructions.Add(new Instruction("bclrl", 0x4C000021, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.CONDITIONREGISTER, Length = 5 }));
            Instructions.Add(new Instruction("blr", 0x4E800020));
            Instructions.Add(new Instruction("bctrl", 0x4E800421));
            Instructions.Add(new Instruction("bctr", 0x4E800420));
            // -------------------------------------------------- C
            Instructions.Add(new Instruction("cmp", 0x7C000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.CONDITIONREGISTER, Length = 3 }, new Instruction.Arg() { Type = Instruction.ArgType.RESERVED, Length = 2 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.BOOL }, new Instruction.Arg() { Index = 3, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 4, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("cmpi", 0x2C000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.CONDITIONREGISTER, Length = 3 }, new Instruction.Arg() { Type = Instruction.ArgType.RESERVED, Length = 2 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.BOOL }, new Instruction.Arg() { Index = 3, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 4, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("cmpl", 0x7C000040, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.CONDITIONREGISTER, Length = 3 }, new Instruction.Arg() { Type = Instruction.ArgType.RESERVED, Length = 2 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.BOOL }, new Instruction.Arg() { Index = 3, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 4, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("cmpli", 0x28000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.CONDITIONREGISTER, Length = 3 }, new Instruction.Arg() { Type = Instruction.ArgType.RESERVED, Length = 2 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.BOOL }, new Instruction.Arg() { Index = 3, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 4, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("cntlzw", 0x7C000034, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("crand", 0x4C000202, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("crandc", 0x4C000102, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("creqv", 0x4C000242, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("crnand", 0x4C0001C2, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("crnor", 0x4C000042, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("cror", 0x4C000382, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("crorc", 0x4C000342, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("crxor", 0x4C000182, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            // -------------------------------------------------- D
            Instructions.Add(new Instruction("dcbf", 0x7C0000AC, new Instruction.Arg() { Type = Instruction.ArgType.RESERVED, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            //Instructions.Add(new Instruction("dcbi", 0x7C0003AC, new Instruction.Arg() { Type = Instruction.ArgType.RESERVED, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }));
            Instructions.Add(new Instruction("dcbt", 0x7C00022C, new Instruction.Arg() { Type = Instruction.ArgType.RESERVED, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("dcbst", 0x7C00006C, new Instruction.Arg() { Type = Instruction.ArgType.RESERVED, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("divw", 0x7C0003D6, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("divw.", 0x7C0003D7, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("divwu", 0x7C000396, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("divwu.", 0x7C000397, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            // -------------------------------------------------- E
            Instructions.Add(new Instruction("eieio", 0x7C0006AC));
            Instructions.Add(new Instruction("eqv", 0x7C000238, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("extsb", 0x7C000774, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("extsb.", 0x7C000775, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("extsh", 0x7C000734, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("extsh.", 0x7C000735, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            // -------------------------------------------------- I
            Instructions.Add(new Instruction("icbi", 0x7C0007AC, new Instruction.Arg() { Type = Instruction.ArgType.RESERVED, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("isync", 0x4C00012C));
            // -------------------------------------------------- L
            Instructions.Add(new Instruction("lbz", 0x88000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("lbzu", 0x8C000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("lbzux", 0x7C0000EE, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("lbzx", 0x7C0000AE, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("lha", 0xA8000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("lhau", 0xAC000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("lhaux", 0x7C0002EE, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("lhax", 0x7C0002AE, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("lhz", 0xA0000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("lhzu", 0xA4000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("lhzux", 0x7C00026E, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("lhzx", 0x7C00022E, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("lmw", 0xB8000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("lwbrx", 0x7C00042C, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("lwz", 0x80000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("lwzu", 0x84000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("lwzux", 0x7C00006E, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("lwzx", 0x7C00002E, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("lwarx", 0x7C000028, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("lfd", 0xC8000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("lfdu", 0xCC000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("lfdux", 0x7C0004EE, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("lfdx", 0x7C0004AE, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("lswi", 0x7C0004AA, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("lswx", 0x7C00042A, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            // -------------------------------------------------- M
            Instructions.Add(new Instruction("mcrf", 0x4C000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.CONDITIONREGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.CONDITIONREGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mfcr", 0x7C000026, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mfctr", 0x7C0902A6, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mflr", 0x7C0802A6, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mfmsr", 0x7C0000A6, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mfspr", 0x7C0002A6, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.SPECIALREGISTER, Length = 5 }, new Instruction.Arg() { Type = Instruction.ArgType.RESERVED, Length = 5 }));
            //Instructions.Add(new Instruction("mfsr", 0x7C0004A6, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            //Instructions.Add(new Instruction("mfsrin", 0x7C000526, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mftbl", 0x7C0C42E6, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mftbu", 0x7C0D42E6, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mtcrf", 0x7C000120, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Type = Instruction.ArgType.RESERVED, Length = 1 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 8 }));
            Instructions.Add(new Instruction("mtctr", 0x7C0903A6, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mtlr", 0x7C0803A6, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mtmsr", 0x7C000124, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mtspr", 0x7C0003A6, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.SPECIALREGISTER, Length = 5 }, new Instruction.Arg() { Type = Instruction.ArgType.RESERVED, Length = 5 }));
            //Instructions.Add(new Instruction("mtsr", 0x7C0001A4, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mulhw", 0x7C000096, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mulhw.", 0x7C000097, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mulhwu", 0x7C000016, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mulhwu.", 0x7C000017, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mulli", 0x1C000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("mullw", 0x7C0001D6, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mullw.", 0x7C0001D7, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mullwo", 0x7C0005D6, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("mullwo.", 0x7C0005D7, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            // -------------------------------------------------- N
            Instructions.Add(new Instruction("nand", 0x7C0003B8, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("nand.", 0x7C0003B9, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("neg", 0x7C0000D0, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("neg.", 0x7C0000D1, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("nego", 0x7C0004D0, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("nego.", 0x7C0004D1, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("nop", 0x60000000));
            Instructions.Add(new Instruction("nor", 0x7C0000F8, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("nor.", 0x7C0000F9, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            // -------------------------------------------------- O
            Instructions.Add(new Instruction("or", 0x7C000378, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("or.", 0x7C000379, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("orc", 0x7C000338, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("orc.", 0x7C000339, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("ori", 0x60000000, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("oris", 0x64000000, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            // -------------------------------------------------- R
            Instructions.Add(new Instruction("rfi", 0x4C000064));
            Instructions.Add(new Instruction("rlwimi", 0x50000000, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 3, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 4, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }));
            Instructions.Add(new Instruction("rlwimi.", 0x50000001, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 3, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 4, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }));
            Instructions.Add(new Instruction("rlwinm", 0x54000000, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 3, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 4, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }));
            Instructions.Add(new Instruction("rlwinm.", 0x54000001, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 3, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 4, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }));
            Instructions.Add(new Instruction("rlwnm", 0x5C000000, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 3, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 4, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }));
            Instructions.Add(new Instruction("rlwnm.", 0x5C000001, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 3, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 4, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }));
            // -------------------------------------------------- S
            Instructions.Add(new Instruction("sc", 0x44000002));
            Instructions.Add(new Instruction("slw", 0x7C000030, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("slw.", 0x7C000031, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("sraw", 0x7C000630, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("srawi", 0x7C000670, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }));
            Instructions.Add(new Instruction("srawi.", 0x7C000671, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }));
            Instructions.Add(new Instruction("srw", 0x7C000430, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("srw.", 0x7C000431, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("stb", 0x98000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("stbu", 0x9C000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("stbux", 0x7C0001EE, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("stbx", 0x7C0001AE, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("sth", 0xB0000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("sthu", 0xB4000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("sthux", 0x7C00036E, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("sthx", 0x7C00032E, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("stmw", 0xBC000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("stw", 0x90000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("stwu", 0x94000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("stwux", 0x7C00016E, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("stwx", 0x7C00012E, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("stwbrx", 0x7C00052C, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("stwcx.", 0x7C00012D, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("stfd", 0xD8000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("stfdu", 0xDC000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("stfdux", 0x7C0005EE, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("stfdx", 0x7C0005AE, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("stswi", 0x7C0005AA, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }));
            Instructions.Add(new Instruction("stswx", 0x7C00052A, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("subf", 0x7C000050, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("subf.", 0x7C000051, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("subfo", 0x7C000450, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("subfo.", 0x7C000451, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("subfc", 0x7C000010, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("subfc.", 0x7C000011, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("subfco", 0x7C000410, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("subfco.", 0x7C000411, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("subfe", 0x7C000110, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("subfic", 0x20000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("subfze", 0x7C000190, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("subfze.", 0x7C000191, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("sync", 0x7C0004AC, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }));
            // -------------------------------------------------- T
            Instructions.Add(new Instruction("tlbia", 0x7C0002E4));
            Instructions.Add(new Instruction("tlbie", 0x7C000264, new Instruction.Arg() { Type = Instruction.ArgType.RESERVED, Length = 10 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("tlbsync", 0x7C00046C));
            Instructions.Add(new Instruction("tw", 0x7C000008, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("twi", 0xC000000, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.IMMEDIATE, Length = 5 }, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            // -------------------------------------------------- X
            Instructions.Add(new Instruction("xor", 0x7C000278, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("xor.", 0x7C000279, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.REGISTER, Length = 5 }));
            Instructions.Add(new Instruction("xori", 0x68000000, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));
            Instructions.Add(new Instruction("xoris", 0x6C000000, new Instruction.Arg() { Index = 1, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 0, Type = Instruction.ArgType.REGISTER, Length = 5 }, new Instruction.Arg() { Index = 2, Type = Instruction.ArgType.IMMEDIATE, Length = 16 }));

            return true;
        }

        public static void LoadExtensions(string path)
        {
            if (Extensions == null)
                Extensions = new List<Extended>();
            else
                Extensions.Clear();

            foreach (string file in System.IO.Directory.GetFiles(path, "*.txt"))
            {
                Extended ex = new PowerPC.Extended(System.IO.Path.GetFileNameWithoutExtension(file), System.IO.File.ReadAllText(file));
                Extensions.Add(ex);
            }
        }
    }
}
