//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWPortable.PowerPC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CWPortable.PowerPC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static string Assemble(string[] args) {
        ///	return &quot;addis &quot; +args[1] + &quot; r0, &quot; + args[2];
        ///}.
        /// </summary>
        internal static string LIS {
            get {
                return ResourceManager.GetString("LIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static string Assemble(string[] args) {
        ///	return &quot;ori &quot; +args[1] + &quot; &quot; + args[1] + &quot; &quot; + args[2].Replace(&quot;,&quot;, &quot;&quot;);
        ///}.
        /// </summary>
        internal static string MR {
            get {
                return ResourceManager.GetString("MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static string Assemble(string[] args) {
        ///	uint v = 0;
        ///	
        ///	if (args[2].IndexOf(&quot;0x&quot;) == 0)
        ///		v = Convert.ToUInt32(args[2].Substring(2), 16);
        ///	else
        ///		v = uint.Parse(args[2]);
        ///		
        ///	return &quot;lis &quot; + args[1] + &quot; 0x&quot; + ((v&amp;0xffff0000)&gt;&gt;16).ToString(&quot;X4&quot;) + &quot;\r\nori &quot; + args[1] + &quot; &quot; + args[1] + &quot; 0x&quot; + (v&amp;0xffff).ToString(&quot;X4&quot;);
        ///}.
        /// </summary>
        internal static string SETREG {
            get {
                return ResourceManager.GetString("SETREG", resourceCulture);
            }
        }
    }
}
